name: Run linter and test

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint code base
        run: npm run lint

      - name: Check types
        run: npm run check-types

      - name: Run tests
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: f77a8a6b35026d3a4c557a7bef1680990303881238f36252f8b2cdf2928618f3
        with:
          coverageCommand: npm run test:ci
