import Button from 'components/Button'
import Field from 'components/controls/Field'
import { Form } from 'components/controls/Form'
import DashboardLayout from 'components/Dashboard/Layout'
import gql from 'graphql-tag'
import { connectServerSideProps } from 'lib/ssg'
import { isEmpty } from 'lodash'
import { useEffect } from 'react'
import QRCode from 'react-qr-code'
import {
  useAddAuthenticatorMutation,
  useCreateOtpProvisioningUriMutation,
  useOtpRequiredQuery,
  useRemoveAuthenticatorMutation,
} from 'types/graphql'

gql`
  query otpRequired {
    viewer {
      id
      otpRequiredForLogin
    }
  }

  mutation createOtpProvisioningUri {
    createOtpProvisioningUri {
      otpProvisioningUri
    }
  }

  mutation addAuthenticator($verificationCode: String!) {
    addAuthenticator(verificationCode: $verificationCode) {
      errors
    }
  }

  mutation removeAuthenticator {
    removeAuthenticator {
      errors
    }
  }
`

const Index = () => {
  const { data, loading, refetch } = useOtpRequiredQuery()

  if (loading) {
    return null
  }

  if (!data?.viewer) {
    return <p>Not logged in</p>
  }

  const connected = data.viewer.otpRequiredForLogin

  return (
    <div className="md:max-w-3xl bg-white p-6 space-y-4">
      {connected ? (
        <RemoveAuthenticator onSuccess={refetch} />
      ) : (
        <AddAuthenticator onSuccess={refetch} />
      )}
    </div>
  )
}

const RemoveAuthenticator = ({ onSuccess }: any) => {
  const [removeAuthenticator] = useRemoveAuthenticatorMutation()

  const handleClick = async () => {
    const { data } = await removeAuthenticator()

    if (isEmpty(data?.removeAuthenticator.errors)) {
      alert('Success!')
      onSuccess()
    } else {
      alert(data?.removeAuthenticator.errors.join(', '))
    }
  }

  return (
    <>
      <p>An authenticator has been added to this account</p>
      <Button type="button" onClick={handleClick}>
        Remove
      </Button>
    </>
  )
}

const OTPForm = ({ onSuccess }: any) => {
  const [addAuthenticator] = useAddAuthenticatorMutation()

  const handleSubmit = async (variables: any, { setSubmitting }: any) => {
    const { data } = await addAuthenticator({ variables })

    if (isEmpty(data?.addAuthenticator.errors)) {
      alert('Success!')
      onSuccess()
    } else {
      alert(data?.addAuthenticator.errors.join(', '))
    }

    setSubmitting(false)
  }

  return (
    <Form id="otpForm" initialValues={{}} onSubmit={handleSubmit}>
      {({ isSubmitting }: { isSubmitting: any }) => (
        <>
          <Field type="input" name="verificationCode" />
          <Button type="submit" loading={isSubmitting} className="mb-2">
            Connect
          </Button>
        </>
      )}
    </Form>
  )
}

const AddAuthenticator = ({ onSuccess }: any) => {
  const [mutate, { data, loading }] = useCreateOtpProvisioningUriMutation()

  useEffect(() => {
    mutate()
  }, [])

  if (loading || !data) {
    return null
  }

  return (
    <>
      <div className="rich-text">
        <p>
          Connect an authenticator app that generates verification codes. You
          can use the codes when we need to verify your identity.
        </p>
        <ol>
          <li>
            Download and install an authenticator app on your mobile device.
          </li>
          <li>Use the app to scan this QR code.</li>
          <li>Enter the code generated by the app.</li>
        </ol>
      </div>
      <div>
        <QRCode value={data.createOtpProvisioningUri.otpProvisioningUri} />
      </div>
      <div>
        <OTPForm onSuccess={onSuccess} />
      </div>
    </>
  )
}

Index.Layout = DashboardLayout
export const getServerSideProps = connectServerSideProps(Index)
export default Index
